! -*- zebra -*-

hostname R4
password en
enable password en


!

interface lo
  ip address 127.0.0.1/32

interface R4-eth1


interface R4-eth2

interface R4-eth3

!

interface R4-eth4

log file /tmp/R4.log

