! -*- zebra -*-

hostname R1
password en
enable password en


!

interface lo
  ip address 127.0.0.1/32

interface R1-eth1

interface R1-eth2


interface R1-eth3

!

interface R1-eth4


interface R1-eth5

log file /tmp/R1.log

