! -*- zebra -*-

hostname R2
password en
enable password en

!

interface lo
  ip address 127.0.0.1/32

interface R2-eth1

interface R2-eth2

interface R2-eth3
!

interface R2-eth4

interface R2-eth5

log file /tmp/R2.log

